# This is a basic workflow to help you get started with Actions

name: Build (Windows/Linux)

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Setup node
        uses: actions/setup-node@v3.5.0

      - name: Install dependencies
        run: npm install nativefier -g
      # Runs a set of commands using the runners shell
      - name: Build (Windows/Linux)
        run: |
          nativefier --update --name "Shell Shockers" --arch x64 --platform windows --user-agent firefox  --internal-urls "(.*?accounts\.google\.com.*?|.*?shellshockio-181719\.firebaseapp\.com.*?)" --single-instance  https://shellshock.io --verbose
          nativefier --update --name "Shell Shockers" --arch x64 --platform linux --user-agent firefox  --internal-urls "(.*?accounts\.google\.com.*?|.*?shellshockio-181719\.firebaseapp\.com.*?)" --single-instance  https://shellshock.io --verbose
      - uses: actions/upload-artifact@v3
        with:
          name: Upload (windows x64)
          path: |
            Shell Shockers-win32-x64/
            Shell Shockers-linux-x64/
          if-no-files-found: error
